docker pull percona/percona-xtradb-cluster:5.7.21



docker network create --subnet=172.36.0.0/24 mysql_group



for port in `seq 2 4`; do \
docker volume create --name mysql_group_${port}
done


# 创建5个PXC容器构成集群
# 第一个节点
docker run -d -p 3402:3306 -e MYSQL_ROOT_PASSWORD=Ou891007 -e CLUSTER_NAME=PXC -e XTRABACKUP_PASSWORD=Ou891007  -v /etc/localtime:/etc/localtime:ro -v mysql_group_2:/var/lib/mysql --name=mysql_group_2 --network=mysql_group --ip 172.36.0.2 percona/percona-xtradb-cluster:5.7.21
# 在第一个节点启动后要等待一段时间，等候mysql启动完成。

docker run -d -p 3403:3306 -e MYSQL_ROOT_PASSWORD=Ou891007 -e CLUSTER_NAME=PXC -e XTRABACKUP_PASSWORD=Ou891007  -v /etc/localtime:/etc/localtime:ro -e CLUSTER_JOIN=mysql_group_2 -v mysql_group_3:/var/lib/mysql --name=mysql_group_3 --net=mysql_group --ip 172.36.0.3 percona/percona-xtradb-cluster:5.7.21


docker run -d -p 3404:3306 -e MYSQL_ROOT_PASSWORD=Ou891007 -e CLUSTER_NAME=PXC -e XTRABACKUP_PASSWORD=Ou891007  -v /etc/localtime:/etc/localtime:ro -e CLUSTER_JOIN=mysql_group_2 -v mysql_group_4:/var/lib/mysql --name=mysql_group_4 --net=mysql_group --ip 172.36.0.4 percona/percona-xtradb-cluster:5.7.21


docker exec -it mysql_group_2 bash

mysql -u root -P 3306 -h 127.0.0.1 -p


集群崩溃
然后我试着启动其他节点，都是闪退
无奈只好去找grastate.dat文件，grastate.data文件在对应的卷_data文件夹下，找到后查看grastate.dat文件发现五个节点safe_bootstrap值全为0，将节点1的grastate.dat中的safe_to_bootstrap修改为1后保存，重启节点1